---
name: WWW-FleXtel
version: 0.03
author:
  - Nicola Worthington <nicolaw@cpan.org>
abstract: Manipulate FleXtel phone number redirection
license: open_source
requires:
  Carp: 0
  Crypt::SSLeay: 0
  LWP::UserAgent: 2.032
  Scalar::Util: 0
recommends:
  Test::Deep: 0.093
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
build_requires:
  Test: 0
  Test::More: 0
provides:
  WWW::FleXtel:
    file: lib/WWW/FleXtel.pm
    version: 0.03
generated_by: Module::Build version 0.2611
