---
name: WWW-FleXtel
version: 0.01
author:
  - 'Nicola Worthington <nicolaw@cpan.org>'
abstract: Manipulate FleXtel phone number redirection
license: open_source
requires:
  Carp: 0
  LWP::UserAgent: 0
  SSLeay: 0
  Scalar::Util: 0
build_requires:
  Test: 0
  Test::More: 0
recommends:
  Test::Deep: 0.093
  Test::Pod: 1.2
  Test::Pod::Coverage: 1.06
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  WWW::FleXtel:
    file: lib/WWW/FleXtel.pm
    version: 0.01
